### ISSUE TITLE
Wrong Time Zone

### ISSUE THREAD

**Issue by rapmann02** [Qrome/marquee-scroller#54] opened 2018-10-30 16:42 UTC
In Switzerland it changes to Winter Time. Example: It is 9:20, Clock shows 10:20

**Comment by Qrome** [comment] 2018-10-30 17:50
This is a duplicate of this one:   https://github.com/Qrome/marquee-scroller/issues/52
Also, there is a dev branch of 2.4 that has the fix.

**Closed by Qrome** 2018-10-30 17:50 UTC
