### ISSUE TITLE
time display and info rotation and update

### ISSUE THREAD

**Issue by Franzsupersport** [Qrome/marquee-scroller#86] opened 2019-02-20 01:54 UTC
Hi,
I made the marquee scroller and the printer monitor in both sizes 0,96 inches and 1,3 inches screen, evrything works fine when i turn it on, but it doesn't display the time and doesn't update the printing process.
If i disconnect power and start it again the printing processs appear updated, but remain in same status after (for example if i turn it on and printing is 60% it will remain 60% unless i reconnect the power).
For the marquee once i turn it on, it shows the weather info correctly, but then shows 2 lines that i guess should be the time (but it doesn't shows the time) and it stays like that forever..
I followed the pin connection strictly and upload the arduino file without problems.

**Comment by Qrome** [comment] 2019-02-20 02:09
Have you looked over at my other project [Printer Monitor](https://github.com/Qrome/printer-monitor)?  That project shows the print status as well as the clock -- just does not do the News.   Someone did a PR where they added the news to that project but I never merged it to the main code base.   It would be easier to add the News to that project than to convert this one to the OLED displays.

Honestly, I don't know if I could help you without seeing the code.

**Comment by Franzsupersport** [comment] 2019-02-20 02:52
Yes, actually i followed both video of Chris Riley on you tube and decided to make both.
of course i followed separately the project since connections and files are different, just i get the same problem on both.
The time doesn't appear, remain only 2 lines -- and stays like that. also as mentioned before, it update the info like weather on marquee and printing status on printer monitor only once when power on, and then never change till you disconnect power and power on again, like if it cannot connect anymore to get updates from the network. i don't know if the problem may be my network of the fact that i actually live in China and here internet is quite restricted..

**Comment by Qrome** [comment] 2019-02-20 06:20
You may need to change the time client as it uses google -- this could be the problem.  I think I have heard others mention problems running it in China.

**Comment by Franzsupersport** [comment] 2019-02-20 06:27
OH, yes it could be the problem, may i ask you how to do it? i don't have much experience with arduino, i just started about 2 months ago and still figuring out how to do everything.. thanks

**Comment by Qrome** [comment] 2019-02-20 15:02
Edit line 44 on the TimeClient.cpp file -- that is where the host name is for getting the time.   Try something else that would work in China.

**Comment by Franzsupersport** [comment] 2019-02-22 00:07
HI again,
i've searched for NTP servers in asia, i managed to find some, but i tried to do as you said and it still doesn't work. I think i'm missing something.. 

 // This will send the request to the server
  client.print(String("GET / HTTP/1.1\r\n") +
               String("Host: 1.cn.pool.ntp.org\r\n") +
               String("Connection: close\r\n\r\n"));
  int repeatCounter = 0;
  while(!client.available() && repeatCounter < 10) {
    delay(1000);
    Serial.println(".");
    repeatCounter++;
  }
is anything else i should change? thanks a lot for the help.

**Comment by magnum129** [comment] 2019-03-22 01:21
as of 2.10 it's been switched to a new time client, that may work for you. Please give it a try.

**Comment by Qrome** [comment] 2019-03-22 03:37
Thanks to @magnum129 -- the Marquee Scroller v2.10 includes TimeZoneDB service that resolves the issue here.

**Comment by dagopeter** [comment] 2019-06-18 20:38
Here I have my problem copied at serial output - it will connect to weather-server and time-server, but at data process comes always message - wrong api key. But I cannot test it on an other modus. What is wrong? 
![serial_output_time_weather_connection](https://user-images.githubusercontent.com/51929544/59718148-cc3e8d80-9219-11e9-8804-055abdf41672.jpg)

**Comment by Qrome** [comment] 2019-06-18 20:58
Have you confirmed that your API key works?   It looks like a valid response telling you that you have an Invalid API key for the TimeZone service.

**Comment by dagopeter** [comment] 2019-06-18 21:10
Hi Qrome - thanks for reply - no, I have an free api key and did not find out how to change it. It seems, that I would have to pay for a regular service - isn't it ?

**Comment by dagopeter** [comment] 2019-06-18 21:14
![timeapi_Key](https://user-images.githubusercontent.com/51929544/59720253-a9fb3e80-921e-11e9-98ce-d188107adc4f.jpg)
.. here it is - all looks good but there is no query, so that it seems that non has used it  - me too :-)

**Comment by dagopeter** [comment] 2019-06-18 21:16
.. I will try it tomorrow to get a new one with another email address perhaps :-)

**Comment by dagopeter** [comment] 2019-06-19 04:39
It is a pitty - also my new API key reacts in the same manner.
![serial_output_time_weather_connection_new_API_KEY](https://user-images.githubusercontent.com/51929544/59737159-d170fc00-925c-11e9-98ec-c9a9c4f21923.jpg)
It must have another reason ....  :-(

**Comment by Qrome** [comment] 2019-06-19 05:20
Sure enough -- you have NOT activated your account with TimeZoneDB -- they send you an email with the KEY in the email -- however just above that they give you a link to activate the account.   If you do not do this, it will not work.   This is how they verify that you have a valid email address on the account.

How do I know this?   I just went through and created another key.   

Go back to your email and click on the activate account link.

**Comment by dagopeter** [comment] 2019-06-19 05:47
Tataaa ... you are right ---- I cannot believe that I had forgotten it twice , but it has to be real :-) In that moment I tipped on that link and restarted my WEMOS Board the right Date and Time happend lightning fas - thank you so much - now I' m happy with this and - sure - I will look at the whole thing much deeper than before :-)

**Comment by Qrome** [comment] 2019-06-19 05:50
Cool, glad it is working for you.   You may want to delete the photos in your posts as they have your key in them.     Thanks for the update.

**Closed by Qrome** 2019-06-19 05:50 UTC

**Comment by dagopeter** [comment] 2019-06-19 07:00
Thank you again - I have deleted it - could be better so :-)  Have a nice time!
