### ISSUE TITLE
LED orientation/rotation

### ISSUE THREAD

**Issue by NickXi** [Qrome/marquee-scroller#78] opened 2019-01-10 07:43 UTC
Had an issue with the LED that I ordered from Ali express was not displaying correctly to fix the issue all i had to do is change in marquee.ino

matrix.setRotation(i, 3);
To
matrix.setRotation(i, 1);

**Comment by Qrome** [comment] 2019-01-10 14:33
Duplicate of #75

**Closed by Qrome** 2019-01-10 14:33 UTC
